// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Dentist is the predicate function for dentist builders.
type Dentist func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Queue is the predicate function for queue builders.
type Queue func(*sql.Selector)
