// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldPatientGender holds the string denoting the patient_gender field in the database.
	FieldPatientGender = "patient_gender"
	// FieldPatientAge holds the string denoting the patient_age field in the database.
	FieldPatientAge = "patient_age"
	// FieldPatientPhone holds the string denoting the patient_phone field in the database.
	FieldPatientPhone = "patient_phone"

	// EdgeQueue holds the string denoting the queue edge name in mutations.
	EdgeQueue = "queue"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// QueueTable is the table the holds the queue relation/edge.
	QueueTable = "queues"
	// QueueInverseTable is the table name for the Queue entity.
	// It exists in this package in order to avoid circular dependency with the "queue" package.
	QueueInverseTable = "queues"
	// QueueColumn is the table column denoting the queue relation/edge.
	QueueColumn = "patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
	FieldPatientGender,
	FieldPatientAge,
	FieldPatientPhone,
}

var (
	// PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
	// PatientGenderValidator is a validator for the "patient_gender" field. It is called by the builders before save.
	PatientGenderValidator func(string) error
	// PatientPhoneValidator is a validator for the "patient_phone" field. It is called by the builders before save.
	PatientPhoneValidator func(int) error
)
