// Code generated by entc, DO NOT EDIT.

package dentist

const (
	// Label holds the string label denoting the dentist type in the database.
	Label = "dentist"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDentistName holds the string denoting the dentist_name field in the database.
	FieldDentistName = "dentist_name"
	// FieldDentistEmail holds the string denoting the dentist_email field in the database.
	FieldDentistEmail = "dentist_email"
	// FieldDentistPhone holds the string denoting the dentist_phone field in the database.
	FieldDentistPhone = "dentist_phone"

	// EdgeQueue holds the string denoting the queue edge name in mutations.
	EdgeQueue = "queue"

	// Table holds the table name of the dentist in the database.
	Table = "dentists"
	// QueueTable is the table the holds the queue relation/edge.
	QueueTable = "queues"
	// QueueInverseTable is the table name for the Queue entity.
	// It exists in this package in order to avoid circular dependency with the "queue" package.
	QueueInverseTable = "queues"
	// QueueColumn is the table column denoting the queue relation/edge.
	QueueColumn = "dentist_id"
)

// Columns holds all SQL columns for dentist fields.
var Columns = []string{
	FieldID,
	FieldDentistName,
	FieldDentistEmail,
	FieldDentistPhone,
}

var (
	// DentistNameValidator is a validator for the "dentist_name" field. It is called by the builders before save.
	DentistNameValidator func(string) error
	// DentistEmailValidator is a validator for the "dentist_email" field. It is called by the builders before save.
	DentistEmailValidator func(string) error
	// DentistPhoneValidator is a validator for the "dentist_phone" field. It is called by the builders before save.
	DentistPhoneValidator func(int) error
)
