// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmployeeName holds the string denoting the employee_name field in the database.
	FieldEmployeeName = "employee_name"
	// FieldEmployeeEmail holds the string denoting the employee_email field in the database.
	FieldEmployeeEmail = "employee_email"
	// FieldEmployeePassword holds the string denoting the employee_password field in the database.
	FieldEmployeePassword = "employee_password"
	// FieldEmployeePhone holds the string denoting the employee_phone field in the database.
	FieldEmployeePhone = "employee_phone"

	// EdgeQueue holds the string denoting the queue edge name in mutations.
	EdgeQueue = "queue"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// QueueTable is the table the holds the queue relation/edge.
	QueueTable = "queues"
	// QueueInverseTable is the table name for the Queue entity.
	// It exists in this package in order to avoid circular dependency with the "queue" package.
	QueueInverseTable = "queues"
	// QueueColumn is the table column denoting the queue relation/edge.
	QueueColumn = "employee_id"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEmployeeName,
	FieldEmployeeEmail,
	FieldEmployeePassword,
	FieldEmployeePhone,
}

var (
	// EmployeeNameValidator is a validator for the "employee_name" field. It is called by the builders before save.
	EmployeeNameValidator func(string) error
	// EmployeePhoneValidator is a validator for the "employee_phone" field. It is called by the builders before save.
	EmployeePhoneValidator func(int) error
)
