// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B5916177/app/ent/dentist"
	"github.com/B5916177/app/ent/queue"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DentistCreate is the builder for creating a Dentist entity.
type DentistCreate struct {
	config
	mutation *DentistMutation
	hooks    []Hook
}

// SetDentistName sets the dentist_name field.
func (dc *DentistCreate) SetDentistName(s string) *DentistCreate {
	dc.mutation.SetDentistName(s)
	return dc
}

// SetDentistEmail sets the dentist_email field.
func (dc *DentistCreate) SetDentistEmail(s string) *DentistCreate {
	dc.mutation.SetDentistEmail(s)
	return dc
}

// SetDentistPhone sets the dentist_phone field.
func (dc *DentistCreate) SetDentistPhone(i int) *DentistCreate {
	dc.mutation.SetDentistPhone(i)
	return dc
}

// AddQueueIDs adds the queue edge to Queue by ids.
func (dc *DentistCreate) AddQueueIDs(ids ...int) *DentistCreate {
	dc.mutation.AddQueueIDs(ids...)
	return dc
}

// AddQueue adds the queue edges to Queue.
func (dc *DentistCreate) AddQueue(q ...*Queue) *DentistCreate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return dc.AddQueueIDs(ids...)
}

// Mutation returns the DentistMutation object of the builder.
func (dc *DentistCreate) Mutation() *DentistMutation {
	return dc.mutation
}

// Save creates the Dentist in the database.
func (dc *DentistCreate) Save(ctx context.Context) (*Dentist, error) {
	if _, ok := dc.mutation.DentistName(); !ok {
		return nil, &ValidationError{Name: "dentist_name", err: errors.New("ent: missing required field \"dentist_name\"")}
	}
	if v, ok := dc.mutation.DentistName(); ok {
		if err := dentist.DentistNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "dentist_name", err: fmt.Errorf("ent: validator failed for field \"dentist_name\": %w", err)}
		}
	}
	if _, ok := dc.mutation.DentistEmail(); !ok {
		return nil, &ValidationError{Name: "dentist_email", err: errors.New("ent: missing required field \"dentist_email\"")}
	}
	if v, ok := dc.mutation.DentistEmail(); ok {
		if err := dentist.DentistEmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "dentist_email", err: fmt.Errorf("ent: validator failed for field \"dentist_email\": %w", err)}
		}
	}
	if _, ok := dc.mutation.DentistPhone(); !ok {
		return nil, &ValidationError{Name: "dentist_phone", err: errors.New("ent: missing required field \"dentist_phone\"")}
	}
	if v, ok := dc.mutation.DentistPhone(); ok {
		if err := dentist.DentistPhoneValidator(v); err != nil {
			return nil, &ValidationError{Name: "dentist_phone", err: fmt.Errorf("ent: validator failed for field \"dentist_phone\": %w", err)}
		}
	}
	var (
		err  error
		node *Dentist
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DentistMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DentistCreate) SaveX(ctx context.Context) *Dentist {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DentistCreate) sqlSave(ctx context.Context) (*Dentist, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DentistCreate) createSpec() (*Dentist, *sqlgraph.CreateSpec) {
	var (
		d     = &Dentist{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: dentist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dentist.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.DentistName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dentist.FieldDentistName,
		})
		d.DentistName = value
	}
	if value, ok := dc.mutation.DentistEmail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dentist.FieldDentistEmail,
		})
		d.DentistEmail = value
	}
	if value, ok := dc.mutation.DentistPhone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: dentist.FieldDentistPhone,
		})
		d.DentistPhone = value
	}
	if nodes := dc.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dentist.QueueTable,
			Columns: []string{dentist.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
