// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/B5916177/app/ent/employee"
	"github.com/B5916177/app/ent/predicate"
	"github.com/B5916177/app/ent/queue"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks      []Hook
	mutation   *EmployeeMutation
	predicates []predicate.Employee
}

// Where adds a new predicate for the builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetEmployeeName sets the employee_name field.
func (eu *EmployeeUpdate) SetEmployeeName(s string) *EmployeeUpdate {
	eu.mutation.SetEmployeeName(s)
	return eu
}

// SetEmployeeEmail sets the employee_email field.
func (eu *EmployeeUpdate) SetEmployeeEmail(s string) *EmployeeUpdate {
	eu.mutation.SetEmployeeEmail(s)
	return eu
}

// SetEmployeePassword sets the employee_password field.
func (eu *EmployeeUpdate) SetEmployeePassword(s string) *EmployeeUpdate {
	eu.mutation.SetEmployeePassword(s)
	return eu
}

// SetEmployeePhone sets the employee_phone field.
func (eu *EmployeeUpdate) SetEmployeePhone(i int) *EmployeeUpdate {
	eu.mutation.ResetEmployeePhone()
	eu.mutation.SetEmployeePhone(i)
	return eu
}

// AddEmployeePhone adds i to employee_phone.
func (eu *EmployeeUpdate) AddEmployeePhone(i int) *EmployeeUpdate {
	eu.mutation.AddEmployeePhone(i)
	return eu
}

// AddQueueIDs adds the queue edge to Queue by ids.
func (eu *EmployeeUpdate) AddQueueIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.AddQueueIDs(ids...)
	return eu
}

// AddQueue adds the queue edges to Queue.
func (eu *EmployeeUpdate) AddQueue(q ...*Queue) *EmployeeUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return eu.AddQueueIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// RemoveQueueIDs removes the queue edge to Queue by ids.
func (eu *EmployeeUpdate) RemoveQueueIDs(ids ...int) *EmployeeUpdate {
	eu.mutation.RemoveQueueIDs(ids...)
	return eu
}

// RemoveQueue removes queue edges to Queue.
func (eu *EmployeeUpdate) RemoveQueue(q ...*Queue) *EmployeeUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return eu.RemoveQueueIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := eu.mutation.EmployeeName(); ok {
		if err := employee.EmployeeNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "employee_name", err: fmt.Errorf("ent: validator failed for field \"employee_name\": %w", err)}
		}
	}
	if v, ok := eu.mutation.EmployeePhone(); ok {
		if err := employee.EmployeePhoneValidator(v); err != nil {
			return 0, &ValidationError{Name: "employee_phone", err: fmt.Errorf("ent: validator failed for field \"employee_phone\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmployeeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employee.Table,
			Columns: employee.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employee.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.EmployeeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeeName,
		})
	}
	if value, ok := eu.mutation.EmployeeEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeeEmail,
		})
	}
	if value, ok := eu.mutation.EmployeePassword(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeePassword,
		})
	}
	if value, ok := eu.mutation.EmployeePhone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: employee.FieldEmployeePhone,
		})
	}
	if value, ok := eu.mutation.AddedEmployeePhone(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: employee.FieldEmployeePhone,
		})
	}
	if nodes := eu.mutation.RemovedQueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.QueueTable,
			Columns: []string{employee.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.QueueTable,
			Columns: []string{employee.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetEmployeeName sets the employee_name field.
func (euo *EmployeeUpdateOne) SetEmployeeName(s string) *EmployeeUpdateOne {
	euo.mutation.SetEmployeeName(s)
	return euo
}

// SetEmployeeEmail sets the employee_email field.
func (euo *EmployeeUpdateOne) SetEmployeeEmail(s string) *EmployeeUpdateOne {
	euo.mutation.SetEmployeeEmail(s)
	return euo
}

// SetEmployeePassword sets the employee_password field.
func (euo *EmployeeUpdateOne) SetEmployeePassword(s string) *EmployeeUpdateOne {
	euo.mutation.SetEmployeePassword(s)
	return euo
}

// SetEmployeePhone sets the employee_phone field.
func (euo *EmployeeUpdateOne) SetEmployeePhone(i int) *EmployeeUpdateOne {
	euo.mutation.ResetEmployeePhone()
	euo.mutation.SetEmployeePhone(i)
	return euo
}

// AddEmployeePhone adds i to employee_phone.
func (euo *EmployeeUpdateOne) AddEmployeePhone(i int) *EmployeeUpdateOne {
	euo.mutation.AddEmployeePhone(i)
	return euo
}

// AddQueueIDs adds the queue edge to Queue by ids.
func (euo *EmployeeUpdateOne) AddQueueIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.AddQueueIDs(ids...)
	return euo
}

// AddQueue adds the queue edges to Queue.
func (euo *EmployeeUpdateOne) AddQueue(q ...*Queue) *EmployeeUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return euo.AddQueueIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// RemoveQueueIDs removes the queue edge to Queue by ids.
func (euo *EmployeeUpdateOne) RemoveQueueIDs(ids ...int) *EmployeeUpdateOne {
	euo.mutation.RemoveQueueIDs(ids...)
	return euo
}

// RemoveQueue removes queue edges to Queue.
func (euo *EmployeeUpdateOne) RemoveQueue(q ...*Queue) *EmployeeUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return euo.RemoveQueueIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	if v, ok := euo.mutation.EmployeeName(); ok {
		if err := employee.EmployeeNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "employee_name", err: fmt.Errorf("ent: validator failed for field \"employee_name\": %w", err)}
		}
	}
	if v, ok := euo.mutation.EmployeePhone(); ok {
		if err := employee.EmployeePhoneValidator(v); err != nil {
			return nil, &ValidationError{Name: "employee_phone", err: fmt.Errorf("ent: validator failed for field \"employee_phone\": %w", err)}
		}
	}

	var (
		err  error
		node *Employee
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmployeeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (e *Employee, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   employee.Table,
			Columns: employee.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: employee.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Employee.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.EmployeeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeeName,
		})
	}
	if value, ok := euo.mutation.EmployeeEmail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeeEmail,
		})
	}
	if value, ok := euo.mutation.EmployeePassword(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: employee.FieldEmployeePassword,
		})
	}
	if value, ok := euo.mutation.EmployeePhone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: employee.FieldEmployeePhone,
		})
	}
	if value, ok := euo.mutation.AddedEmployeePhone(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: employee.FieldEmployeePhone,
		})
	}
	if nodes := euo.mutation.RemovedQueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.QueueTable,
			Columns: []string{employee.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.QueueTable,
			Columns: []string{employee.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Employee{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
