// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/B5916177/app/ent/dentist"
	"github.com/B5916177/app/ent/employee"
	"github.com/B5916177/app/ent/patient"
	"github.com/B5916177/app/ent/queue"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Queue is the model entity for the Queue schema.
type Queue struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Dental holds the value of the "dental" field.
	Dental string `json:"dental,omitempty"`
	// QueueTime holds the value of the "queue_time" field.
	QueueTime time.Time `json:"queue_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QueueQuery when eager-loading is set.
	Edges       QueueEdges `json:"edges"`
	dentist_id  *int
	employee_id *int
	patient_id  *int
}

// QueueEdges holds the relations/edges for other nodes in the graph.
type QueueEdges struct {
	// Dentist holds the value of the dentist edge.
	Dentist *Dentist
	// Employee holds the value of the employee edge.
	Employee *Employee
	// Patient holds the value of the patient edge.
	Patient *Patient
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DentistOrErr returns the Dentist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QueueEdges) DentistOrErr() (*Dentist, error) {
	if e.loadedTypes[0] {
		if e.Dentist == nil {
			// The edge dentist was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: dentist.Label}
		}
		return e.Dentist, nil
	}
	return nil, &NotLoadedError{edge: "dentist"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QueueEdges) EmployeeOrErr() (*Employee, error) {
	if e.loadedTypes[1] {
		if e.Employee == nil {
			// The edge employee was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: employee.Label}
		}
		return e.Employee, nil
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QueueEdges) PatientOrErr() (*Patient, error) {
	if e.loadedTypes[2] {
		if e.Patient == nil {
			// The edge patient was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: patient.Label}
		}
		return e.Patient, nil
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Queue) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // dental
		&sql.NullTime{},   // queue_time
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Queue) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // dentist_id
		&sql.NullInt64{}, // employee_id
		&sql.NullInt64{}, // patient_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Queue fields.
func (q *Queue) assignValues(values ...interface{}) error {
	if m, n := len(values), len(queue.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	q.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field dental", values[0])
	} else if value.Valid {
		q.Dental = value.String
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field queue_time", values[1])
	} else if value.Valid {
		q.QueueTime = value.Time
	}
	values = values[2:]
	if len(values) == len(queue.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field dentist_id", value)
		} else if value.Valid {
			q.dentist_id = new(int)
			*q.dentist_id = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field employee_id", value)
		} else if value.Valid {
			q.employee_id = new(int)
			*q.employee_id = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field patient_id", value)
		} else if value.Valid {
			q.patient_id = new(int)
			*q.patient_id = int(value.Int64)
		}
	}
	return nil
}

// QueryDentist queries the dentist edge of the Queue.
func (q *Queue) QueryDentist() *DentistQuery {
	return (&QueueClient{config: q.config}).QueryDentist(q)
}

// QueryEmployee queries the employee edge of the Queue.
func (q *Queue) QueryEmployee() *EmployeeQuery {
	return (&QueueClient{config: q.config}).QueryEmployee(q)
}

// QueryPatient queries the patient edge of the Queue.
func (q *Queue) QueryPatient() *PatientQuery {
	return (&QueueClient{config: q.config}).QueryPatient(q)
}

// Update returns a builder for updating this Queue.
// Note that, you need to call Queue.Unwrap() before calling this method, if this Queue
// was returned from a transaction, and the transaction was committed or rolled back.
func (q *Queue) Update() *QueueUpdateOne {
	return (&QueueClient{config: q.config}).UpdateOne(q)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (q *Queue) Unwrap() *Queue {
	tx, ok := q.config.driver.(*txDriver)
	if !ok {
		panic("ent: Queue is not a transactional entity")
	}
	q.config.driver = tx.drv
	return q
}

// String implements the fmt.Stringer.
func (q *Queue) String() string {
	var builder strings.Builder
	builder.WriteString("Queue(")
	builder.WriteString(fmt.Sprintf("id=%v", q.ID))
	builder.WriteString(", dental=")
	builder.WriteString(q.Dental)
	builder.WriteString(", queue_time=")
	builder.WriteString(q.QueueTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Queues is a parsable slice of Queue.
type Queues []*Queue

func (q Queues) config(cfg config) {
	for _i := range q {
		q[_i].config = cfg
	}
}
