// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DentistsColumns holds the columns for the "dentists" table.
	DentistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dentist_name", Type: field.TypeString},
		{Name: "dentist_email", Type: field.TypeString},
		{Name: "dentist_phone", Type: field.TypeInt},
	}
	// DentistsTable holds the schema information for the "dentists" table.
	DentistsTable = &schema.Table{
		Name:        "dentists",
		Columns:     DentistsColumns,
		PrimaryKey:  []*schema.Column{DentistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "employee_name", Type: field.TypeString},
		{Name: "employee_email", Type: field.TypeString, Unique: true},
		{Name: "employee_password", Type: field.TypeString},
		{Name: "employee_phone", Type: field.TypeInt},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:        "employees",
		Columns:     EmployeesColumns,
		PrimaryKey:  []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "patient_name", Type: field.TypeString},
		{Name: "patient_gender", Type: field.TypeString},
		{Name: "patient_age", Type: field.TypeInt},
		{Name: "patient_phone", Type: field.TypeInt},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:        "patients",
		Columns:     PatientsColumns,
		PrimaryKey:  []*schema.Column{PatientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// QueuesColumns holds the columns for the "queues" table.
	QueuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dental", Type: field.TypeString},
		{Name: "queue_time", Type: field.TypeTime},
		{Name: "dentist_id", Type: field.TypeInt, Nullable: true},
		{Name: "employee_id", Type: field.TypeInt, Nullable: true},
		{Name: "patient_id", Type: field.TypeInt, Nullable: true},
	}
	// QueuesTable holds the schema information for the "queues" table.
	QueuesTable = &schema.Table{
		Name:       "queues",
		Columns:    QueuesColumns,
		PrimaryKey: []*schema.Column{QueuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "queues_dentists_queue",
				Columns: []*schema.Column{QueuesColumns[3]},

				RefColumns: []*schema.Column{DentistsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "queues_employees_queue",
				Columns: []*schema.Column{QueuesColumns[4]},

				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "queues_patients_queue",
				Columns: []*schema.Column{QueuesColumns[5]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DentistsTable,
		EmployeesTable,
		PatientsTable,
		QueuesTable,
	}
)

func init() {
	QueuesTable.ForeignKeys[0].RefTable = DentistsTable
	QueuesTable.ForeignKeys[1].RefTable = EmployeesTable
	QueuesTable.ForeignKeys[2].RefTable = PatientsTable
}
