// Code generated by entc, DO NOT EDIT.

package queue

const (
	// Label holds the string label denoting the queue type in the database.
	Label = "queue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDental holds the string denoting the dental field in the database.
	FieldDental = "dental"
	// FieldQueueTime holds the string denoting the queue_time field in the database.
	FieldQueueTime = "queue_time"

	// EdgeDentist holds the string denoting the dentist edge name in mutations.
	EdgeDentist = "dentist"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"

	// Table holds the table name of the queue in the database.
	Table = "queues"
	// DentistTable is the table the holds the dentist relation/edge.
	DentistTable = "queues"
	// DentistInverseTable is the table name for the Dentist entity.
	// It exists in this package in order to avoid circular dependency with the "dentist" package.
	DentistInverseTable = "dentists"
	// DentistColumn is the table column denoting the dentist relation/edge.
	DentistColumn = "dentist_id"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "queues"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_id"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "queues"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
)

// Columns holds all SQL columns for queue fields.
var Columns = []string{
	FieldID,
	FieldDental,
	FieldQueueTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Queue type.
var ForeignKeys = []string{
	"dentist_id",
	"employee_id",
	"patient_id",
}
