export * from './ControllersQueue';
export * from './EntDentist';
export * from './EntDentistEdges';
export * from './EntEmployee';
export * from './EntEmployeeEdges';
export * from './EntPatient';
export * from './EntPatientEdges';
export * from './EntQueue';
export * from './EntQueueEdges';
